---
- name: Install jellyfin (Debian)
  import_tasks: Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install jellyfin (non-Debian)
  ansible.builtin.package:
    name: jellyfin
    state: present
  when: ansible_os_family != 'Debian'

- name: Ensure jellyfin is enabled on boot
  ansible.builtin.service:
    name: jellyfin
    enabled: true
    state: started
